server:
  port: 8083

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/pickupdb?useSSL=false&serverTimezone=UTC
#    username: root
#    password: rootpassword
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  redis:
#    host: localhost
#    port: 6379
#
#  kafka:
#    bootstrap-servers: localhost:9092
